language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache/files"

env:
  - COMPOSER_FLAGS="--prefer-stable"

php:
  - 7.2

matrix:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
      env: COMPOSER_FLAGS=""
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="3.4.x-dev"
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="4.4.x-dev"
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="dev-master"

before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/simple-phpunit
